### ISSUE TITLE
rename lcgPertub to lcgPerturb

### ISSUE THREAD

**Issue by waynevanson** [no-day/fp-ts-lcg#2]
From what I've read, I believe the term is `perturb` and not `pertub`.

from Haskell's QuickCheck: https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck-Arbitrary.html#t:CoArbitrary

Also I'm using this library in [`fp-ts-test`](https://github.com/waynevanson/fp-ts-test), so thank you for making this!

**Comment by m-bock** [comment]
great to hear that you use fp-ts-lcg in your fp-ts-test library. I'll follow your project.

Maybe this one is of interest as well: [fp-ts-generators](https://github.com/no-day/fp-ts-generators)
The idea was that generators are not testing specific and can be used in many fields. So the plan was to build testing libraries on top.

**Comment by waynevanson** [comment]
Oh man that's lit, I'll have to use it! 

Comparing the code, it looks like I made a mistake mistake the string primitive. How embarrassing!
